services:
  mp3-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - mp3-php-fpm
    ports:
      - "81:80"
    networks:
      customnetwork:
        ipv4_address: 172.10.0.10

  mp3-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    environment:
      APP_DEBUG: 1
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      customnetwork:
        ipv4_address: 172.10.0.12
  mp3-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    environment:
      APP_DEBUG: 1
    env_file:
      - .env
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    networks:
      customnetwork:
        ipv4_address: 172.10.0.11
  mp3-postgres:
    image: postgres:17.2-alpine
    volumes:
      - mp3-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
    networks:
      customnetwork:
        ipv4_address: 172.10.0.13
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9005:9000" # API порт
      - "9006:9001" # Консольный порт
    environment:
      MINIO_ROOT_USER: minioadmin # Имя пользователя
      MINIO_ROOT_PASSWORD: minioadmin # Пароль
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data # Хранение данных MinIO
    networks:
      customnetwork:
        ipv4_address: 172.10.0.20
volumes:
  mp3-postgres:
  composer:
  minio-data:
    driver: local
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.10.0.0/16
